name: build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Check on ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.58.1 # MSRV
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Install ${{ matrix.rust }}
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal --component rustfmt,clippy
          rustup default ${{ matrix.rust }}
      - name: Run cargo check
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo check

      - name: Run cargo fmt
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        # Run clippy only on stable to ignore unreasonable old warnings.
        continue-on-error: ${{ matrix.rust != 'stable' }}
        run: cargo clippy -- -D warnings -W clippy::nursery

      - name: Run cargo test
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo test --release

      - name: Run cargo test (intrinsics)
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo test --release --features intrinsics
        env:
          RUSTDOCFLAGS: '-C target-cpu=native'

      - name: Run cargo doc
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: '--html-in-header katex.html'

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
      - name: Run cargo publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
